# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Pass SwiftLint"
  lane :code_linting do
    swiftlint(
        mode: :lint,
        config_file: ".swiftlint.yml",
        raise_if_swiftlint_error: true
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(
         workspace: "MLMini.xcworkspace",
         scheme: "MLMini",
         devices: [ "iPhone 13 mini (16.2)" ],
         clean: false
    )
  end
end